### PR TITLE
LLVM 4 PR

### PR DESCRIPTION
**Pull request by jcarlson23**
@caballa So here is an LLVM-4 PR.  Generally I think this is straightforward.  One place I probably would call out is that I fully replaced Pass.cpp in /tools/opt/, replacing it with the 4.0 PassBuilder.cpp/h files as in 4.0 there's been further progress on the new pass manager and while this means there are more code, that is potentially not used, it didn't seem unwise to cut it out when some might prove useful (and is in the llvm src)...

Please feel free to push back, etc, I still don't have a full compile for crab-llvm, but llvm-seahorn compiles cleanly at this point and so I think it's fine to share as a branch (not master just yet)...

Hope this helps!

### CODE REVIEW

**Comment by agurfinkel** [comment]
Hey @jcarlson23, this looks like a lot of work! 

I can't tell immediately, what has happened to our changes to the InstCombine pass? Are they preserved or replaced by default LLVM behavior? In particular, we have added a flag `AvoidBv` which turns off optimizations that introduce bitvector operations. At a first glance, it seems that these changes have disappeared.

**Comment by jcarlson23** [comment]
@agurfinkel ok, let me do a detailed diff with that in mind.  At some points I started from the 4 source depending on errors I was seeing, The DI (Debug Information) API for instance changed quite a bit, so completely possible I got too aggressive in certain places...

Won't take me long but heading into the weekend I might not get a chance for a few couple days.  Get back to you soon though!

**Comment by jcarlson23** [comment]
Ok, yeah, I got too aggressive.... Closing PR, but shouldn't be too hard to put this back but will go closer with the diff...  Thanks @agurfinkel

**Comment by agurfinkel** [comment]
It might be easier to port our changes to LLVM 4.0 code than to port LLVM 4.0 to our changes. This is what I had to do when migrating from 2.9 to 3.6.

**Comment by jcarlson23** [comment]
Yeah, I think that's right...   My little magic act (the disappearance) was that in some of the 4.0 files, with the 4.0 source being very similar and so I just started grabbing large portions of 4.0 code and importing it right in.  I mean, I was viewing it as you said, if I can replace 3.6 with 4.0 code that's what I wanted....

But..  I erred, one because I dropped some of the nuances you want, replacing it with 4.0, like the`AvoidBv` variable, but also because in 4.0 passes are used more in Chandler's vision, so what I need to do is transfer nuances from the InstCombine.h into InstCombineInternal.h - a new file - which is where the `AssumptionCache` has moved, etc...  

So yeah, I got carried away, bringing in 4.0 pass manager changes, except for the internal header...  But I think once I can resolve the internals to the InstCombiner correctly, then I think the rest isn't too bad - as I said, most of the InstCombiner in 4.0 isn't all that different from 3.6.  I just got too aggressive in bringing in 4.0 code without respecting the changes you want...

At least that's where I am right now, but thanks a bunch!  I'd just love to see this used, it's good stuff...

Sorry for the false start... busy weekend coming up but I'm just plain stubborn so I'll keep after it.

**Pull request closed without merging**
